### ISSUE TITLE
[wx-bf] Error

### ISSUE THREAD

**Issue by pathumego** [BlackFoundry/trufont#15]
```
Traceback (most recent call last):
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/bin/trufont", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/ENV_DIR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fs<3,>=2.2.0; extra == "ufo"' distribution was not found and is required by fonttools

```

**Comment by davelab6** [comment]
"pkg_resources.DistributionNotFound: The 'fs<3,>=2.2.0; extra == "ufo"'
distribution was not found and is required by fonttools"

How did you install fonttools?

**Comment by pathumego** [comment]
`fonttools-3.36.0` installed from pypi. Do I need to build from source?

**Comment by davelab6** [comment]
Try installing with

`pip install -e .`

After cloning GitHub.com/fonttools/fonttools

**Comment by pathumego** [comment]
I installed fonttools from source,  tfont from blackfoundry/tfont source and ufoLib2 and it works! requierments.txt dose not include ufoLib2
