### ISSUE TITLE
[wx-bf] Glyph window not loading

### ISSUE THREAD

**Issue by pathumego** [BlackFoundry/trufont#16]
```
Traceback (most recent call last):
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/src/trufont/controls/glyphContextView.py", line 410, in OnPaint
    drawTextCursor = self.drawingAttribute("showTextCursor")
  File "/Users/macbookpro/src/github/BlackFoundry/trufont/src/trufont/controls/glyphCanvasView.py", line 64, in drawingAttribute
    toolOverride = self._currentTool.drawingAttribute(attr)
AttributeError: 'GlyphCanvasView' object has no attribute '_currentTool'
```

**Comment by davelab6** [comment]
What user actions trigger this?

**Comment by pathumego** [comment]
Clicking on a glyph to open the glyph window triggers the above. This is what I'm seeing;

<img width="1374" alt="screen shot 2019-01-28 at 8 56 38 am" src="https://user-images.githubusercontent.com/6846609/51813106-a51f0800-22da-11e9-8727-f6e0e19f1528.png">

**Comment by pathumego** [comment]
Any update on this?

**Comment by BlackFoundry** [comment]
cannot reproduce this @pathumego 
What system configuration ?
